env:
  global:
  - secure: nfr+bkR5amyrXz37XKtr5D51DcyCTIug65+AJbBiD6u+ijeuLlELzB+Cu65QqlK7l/HfaB5eS8ZW7heal8Bwk1HoZ/vF86Z0+mzLlxVWZPl4mxHQCS3uUfK+XpiczW62K8anUNYk18Tgo18ylp+NDOjUARW9R7Pp/d7COKTt2b3J+noEYL3MXL1Y/+jpupvMbXQTie4ng9oXZ2CbqcBS5xp9YF1pWh+iv0BESu8SuJ1r+2qzlx3qvMMvkez4LAifluSmbqlSlWYen0f3SWnDMoj0SgAZrGED+V4eSrH+8pssZjFFpF0gMBLp240ZH1Swh0jqZZ9E6DwL+DBFngthLh9Ovq9mvJ6/dj3hhTzBlJGpIUcg+xDXrrE88fqlvwurSvaID57zCXGP/86Ar4YPuFlyYU1gK5ymjl/YaShLQ27dY1iYKg/XzjlrjjtHmiktGTEOnCgG+wAj02aMF+KtVbh/cp5ZzdXdyPbPWFjIHE+k2exon2bLT2i3p1USkAkLexmK5ggwiu+OVs5baorp9h/6qUTHDvilX4DuBpVbWuPlpQt8yJFUpAJN0tj+fk811hUS49EZXLuqJb9zfp0ho2gK59Hh+zOrs+3kn+cu5k/ZKVC4C5aZSiZs65/RIjJFlULWgBweGFygD2DZBve4/DAkECcIYVIjLwmDPnj8YlA=
  - secure: XHfyVyamc+bA3Cpd5BCHGKbVzt7JdCj2rYoWUdemt0XMxYMIi7l0eL/IZ1+Ri60zsl7AISTj4wSJYr8YCZDLgXQC9821a6cKcPZ1BKcBXrB7+KjPbPYrSpkJQtOJ1UoVkazYgJhJGQcUGUjqzPSIl+crl3/63kqaIxUqUKZh048f9vAaSYY2LJ/ybA+VczXycyHadiqQojIOPIm7zSR5N6Ry73YrK3F258ls6FTmLKBGyLnnzCEq7OHlKlXTjITs+jp55LWxQ7e7DQW5+E6wpn3uHzTFBxsI18Ps2fvua9DQCBAdWJm0bvC5ShLDsKfKGfBvh0V2ZrkuMMQiCKNdgcJtcOz8zP7jlM5jn7dXK0NwTGDB8gePURoCE2YEf5oyZsQ172zNowB0HU21Z6rRqmJCxz6Oj93VJ2KUEPtOfg/zIKx/M1AX+MQRsGX5xKDQwhYMf0HZ3lR+tBmoOpsPuYkMWAC4vwk601gZPmd1RQz593Z0UTGeseBnt2DPc4ZU0I1t4SEXTFBhl7nnqb9qH3yiEvTivUPtwZxtdqb3+P/V1c0dck+h7s5SvYC+QvmD0XAb6H2TmA+RbOW59RAQyMY68oM/0Jb/sx81guWrtcOCcbt1KZYgHq0fbb7dH12nNDxeWXBnKQLpiVDCEjzQnj/V1T9mHtQlbiDIOpqJ0Ck=
    
stages:
- test
- name: build_staging
  if: branch = development AND type = push
- name: build_release
  if: branch = master AND type = push
jobs:
  include:
  - stage: test
    name: xUnit Tests
    language: csharp
    solution: ladders.sln
    mono: none
    dotnet: 2.1
    script:
    - dotnet restore
  - stage: build_staging
    name: Build docker staging image
    sudo: required
    services:
    - docker
    script:
    - "./bin/docker.sh staging"
  - stage: build_release
    name: Build docker release image
    sudo: required
    services:
    - docker
    script:
    - "./bin/docker.sh latest"
notifications:
  slack: sem5640-2018:iSwMM5tPZh52WE5kVelricok
